services:
  backend:
   build: ./backend 
   env_file:
     - backend/.env
   ports:
     - "5000:5000"
 
  mongo:
   image: mongo
   volumes:
     - mongo-data:/data/db

  nginx:
   build: ./nginx
   ports:
     - "80:80"
   depends_on:
     - backend
     
volumes:
   mongo-data:
 